### ISSUE TITLE
Sorry for being a noob, but...

### ISSUE THREAD

**Issue by debugojira** [avolmensky/panasonic_eolia#3]
I downloaded this from HACS and added it to the configuration.yaml (and also added my password to the secrets.yaml)
I know I'm probably missing something really obvious but do I need to take any further steps?
It doesn't show up in any fashion in devices or entities.
I'm in Japan and have an Eolia air conditioner so I'm very keen to get this working!
Any help would be greatly appreciated

**Comment by avolmensky** [comment]
Is anything coming up in the logs?

**Comment by debugojira** [comment]
2023-02-03 22:44:53.211 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration panasonic_eolia which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

If it helps I'm running Home Assistant OS in a virtual machine on a QNAP NAS. I can't stress how much of a noob I am so it potentially could be something really simple I'm overlooking.

**Comment by avolmensky** [comment]
Is that the only thing in the logs? Try restarting home assistant and checking the logs again

**Comment by debugojira** [comment]
Restarting it I just got this message in the logs:

Logger: homeassistant.components.climate
Source: runner.py:128
Integration: Climate (documentation, issues)
First occurred: 21:37:51 (1 occurrences)
Last logged: 21:37:51

Setup of climate platform panasonic_eolia is taking over 10 seconds.

**Comment by avolmensky** [comment]
Hard to say without any type of error in the log or anything. I'd just check the config is correct, maybe put your password in the main config file for now.

**Comment by debugojira** [comment]
It has shown up in my devices now but when I try to execute commands from the dashboard it comes up with errors:

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/panasonic_eolia/climate.py:240
Integration: panasonic_eolia (documentation, issues)
First occurred: 19:55:36 (1 occurrences)
Last logged: 19:55:36

Error executing service: <ServiceCall climate.set_hvac_mode (c:01GRGK5KQZKAQ4SABYJT5MSZY4): entity_id=['climate.eakon'], hvac_mode=off>
Traceback (most recent call last):
  File "/config/custom_components/panasonic_eolia/climate.py", line 52, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_eolia/climate.py", line 240, in set_hvac_mode
    self._api.set_device(
  File "/usr/local/lib/python3.10/site-packages/panasoniceolia/session.py", line 314, in set_device
    raise ResponseError(response.status_code, response.text)
panasoniceolia.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"E-21291-00007","message":"アプリケーションエラーが発生しました。ご迷惑をおかけし申し訳ございません。"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1805, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 497, in async_set_hvac_mode
    await self.hass.async_add_executor_job(self.set_hvac_mode, hvac_mode)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_eolia/climate.py", line 55, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_eolia/climate.py", line 240, in set_hvac_mode
    self._api.set_device(
  File "/usr/local/lib/python3.10/site-packages/panasoniceolia/session.py", line 314, in set_device
    raise ResponseError(response.status_code, response.text)
panasoniceolia.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"E-21291-00007","message":"アプリケーションエラーが発生しました。ご迷惑をおかけし申し訳ございません。"}

**Comment by avolmensky** [comment]
Is it happening for every mode (Heat/Cool/Auto)? Or only in certain situations?

**Comment by debugojira** [comment]
It's happening for everything

**Comment by avolmensky** [comment]
Are you able to try running the python library directly?

https://github.com/avolmensky/python-panasonic-eolia

**Comment by kouiti** [comment]
I also get the same error and can't use

 Invalid response, status code: 400 - Data: {"code":"E-21291-00007","message":"アプリケーションエラーが発生しました。ご迷惑をおかけし申し訳ございません。"}

I get the same error when using it from the python library.

Is there any solution?

**Comment by avolmensky** [comment]
I'm not actually sure what is the problem here. Maybe we are sending data that is not supported by your particular model of AC? It's going to be hard for me to work out the problem without having the same model. 

Some reverse engineering might be required from your end on this one.

**Comment by avolmensky** [comment]
@kouiti @debugojira
I'm not sure if you ever got this to work. I suspect the problem you have is due to you having echonet on your AC. In that case, you do not need to use this plugin, you can use echonet directly from HA.

You can check if echonet is available on your AC here: https://panasonic.jp/aircon/hems/list.html
